version: "3"

services:
  db-mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_HOST: %
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net
  test-app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - db-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/mydb?useSSL=false&allowPublicKeyRetrievla=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net: